### ISSUE TITLE
Add command-line parameter to pass output directory

### ISSUE THREAD

**Issue by stepanbenes** [MartinDoskar/QuiltingDesign#3]
Currently, all output files (i.e. sample*X*.tpg, tile*X*.tpg) are created in the _current_ directory. Output directory should be made configurable to be able to use the program on a remote server.

**Comment by MartinDoskar** [comment]
Just quick question: is it really just the output directory or should I also add option for path/directory to the input file? In any case, I will probably provide some const string with file name stencils and file extensions.

**Comment by stepanbenes** [comment]
I expect to call the program in similar way to this:
```
./QuiltingDesign.exe "C:/.../input.json" "C:/.../specimen.bmp" "C:/.../"
```
First two parameters should be **absolute** paths to input file (as discussed in #1) and specimen image. Third parameter should be **absolute** path to output directory, where the output files will be generated. 

Output file *names* should be predictable (e.g. `tile{X}.bmp` where `X` is tile id).

**Comment by MartinDoskar** [comment]
Is it necessary to include the absolute path to the specimen image? It should be provided in `C:/.../input.json`, shouldn't it?

**Comment by stepanbenes** [comment]
Currently input.json contains uri to image stored in database. I need to download it to local directory, convert it to desired format and after that pass it to your program. I could update the input.json to point to local file but I don't like it much, it does not seem clean. :)

I don't know. Maybe I lack the insight and can't imagine future use cases concerning input file format. I just focus on this simple image synthesis scenario... :/
