### ISSUE TITLE
Consider using different image format

### ISSUE THREAD

**Issue by stepanbenes** [MartinDoskar/QuiltingDesign#6]
Textified rgb image format is very bulky. Besides the standard formats (_png_, _jpg_, _bmp_) which are not easy to deal with in C++, other simpler compressed formats can be used, e.g. base64-encoded rgb values or binary values directly.

**Comment by MartinDoskar** [comment]
I have struggled with char (especially with converting int to char with casting) so I have resorted to uint8_t. Is it compatible with your framework? Storing binary data with int didn't save much memory compared to the text format (2141KB -> 1876 KB), uint_8 made significant difference (2141KB -> 469KB).

**Comment by stepanbenes** [comment]
Well done.
I think `uint8_t` is just an alias for `unsigned char`. See: [http://stackoverflow.com/questions/1725855/uint8-t-vs-unsigned-char](http://stackoverflow.com/questions/1725855/uint8-t-vs-unsigned-char).

However, I was thinking - if you are going to parse binary data representing rgb values, why not use standard well-known format for this purpose - BMP?

I've forked your repository and tried to implement support for BMP. It seems to work, see this pull request: #7.
